//! Shell alias generation for Claude providers.
//!
//! Generates a shell script (`~/.cc-switch/aliases.sh`) containing shell functions
//! for each non-current Claude provider that has an alias configured. This allows
//! users to run multiple providers simultaneously by using different terminal commands.
//!
//! Usage example:
//! - Current provider (Kimi) → `claude` command (already configured globally)
//! - Alibaba provider with alias "alibaba" → `claude-alibaba` function
//! - DeepSeek provider with alias "deepseek" → `claude-deepseek` function

use crate::config::get_app_config_dir;
use crate::error::AppError;
use crate::provider::Provider;
use indexmap::IndexMap;
use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const SOURCE_MARKER: &str = "# cc-switch shell aliases";
const PATH_MARKER: &str = "# cc-switch alias bin";
const SCRIPT_HEADER: &str = "# Generated by cc-switch — do not edit manually";

/// Generate the shell script content for all non-current Claude providers with an alias set.
///
/// The current provider is excluded because it already maps to the global `claude` command
/// (written to `~/.claude/settings.json` by cc-switch).
pub fn generate_aliases_script(
    providers: &IndexMap<String, Provider>,
    current_id: &str,
) -> String {
    let mut lines = Vec::new();
    lines.push(SCRIPT_HEADER.to_string());
    lines.push("# Each function below invokes `claude` with a specific provider's environment variables.".to_string());
    lines.push("# The current active provider is already mapped to the `claude` command.".to_string());
    lines.push(String::new());

    let mut has_any = false;

    for alias_command in collect_alias_commands(providers, current_id) {
        has_any = true;
        lines.push(format!("{}() {{", alias_command.command_name));
        for (k, v) in &alias_command.env_vars {
            lines.push(format!("  {}={} \\", k, shell_quote(v)));
        }
        lines.push(r#"  claude "$@""#.to_string());
        lines.push("}".to_string());
        lines.push(String::new());
    }

    if !has_any {
        lines.push("# No aliases configured. Set an alias on a Claude provider to generate functions here.".to_string());
    }

    lines.join("\n")
}

/// Extract env vars from a Claude provider's settingsConfig.env, in a stable order.
///
/// Returns only non-empty values. Sensitive fields (API keys) are included as-is
/// since the file is stored in the user's home directory.
fn extract_env_vars(provider: &Provider) -> Vec<(String, String)> {
    let env = match provider.settings_config.get("env") {
        Some(e) => e,
        None => return vec![],
    };

    let priority_keys = [
        "ANTHROPIC_BASE_URL",
        "ANTHROPIC_AUTH_TOKEN",
        "ANTHROPIC_API_KEY",
        "ANTHROPIC_MODEL",
        "ANTHROPIC_REASONING_MODEL",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL",
        "ANTHROPIC_DEFAULT_SONNET_MODEL",
        "ANTHROPIC_DEFAULT_OPUS_MODEL",
    ];

    let mut result = Vec::new();
    for key in &priority_keys {
        if let Some(val) = env.get(key).and_then(|v| v.as_str()) {
            if !val.is_empty() {
                result.push((key.to_string(), val.to_string()));
            }
        }
    }

    // Also pick up any extra keys not in the priority list
    if let Some(obj) = env.as_object() {
        for (k, v) in obj {
            if priority_keys.contains(&k.as_str()) {
                continue; // already added
            }
            if let Some(s) = v.as_str() {
                if !s.is_empty() {
                    result.push((k.clone(), s.to_string()));
                }
            }
        }
    }

    result
}

/// Minimally quote a shell value: wrap in single quotes and escape embedded single quotes.
fn shell_quote(s: &str) -> String {
    // Use single quotes for safety; escape any embedded single quotes as '\''
    let escaped = s.replace('\'', r"'\''");
    format!("'{escaped}'")
}

#[derive(Debug, Clone)]
struct AliasCommand {
    command_name: String,
    env_vars: Vec<(String, String)>,
}

fn collect_alias_commands(
    providers: &IndexMap<String, Provider>,
    current_id: &str,
) -> Vec<AliasCommand> {
    let mut commands = Vec::new();
    for (id, provider) in providers {
        if id.as_str() == current_id {
            continue;
        }

        let alias_name = match &provider.alias {
            Some(a) if !a.trim().is_empty() => a.trim().to_string(),
            _ => continue,
        };

        let env_vars = extract_env_vars(provider);
        if env_vars.is_empty() {
            continue;
        }

        commands.push(AliasCommand {
            command_name: format!("claude-{alias_name}"),
            env_vars,
        });
    }
    commands
}

fn generate_launcher_script(command: &AliasCommand) -> String {
    let mut lines = vec![
        "#!/bin/sh".to_string(),
        SCRIPT_HEADER.to_string(),
        format!("# Command: {}", command.command_name),
        String::new(),
    ];

    for (key, value) in &command.env_vars {
        lines.push(format!("export {}={}", key, shell_quote(value)));
    }

    lines.push(r#"exec claude "$@""#.to_string());
    lines.push(String::new());
    lines.join("\n")
}

/// Write the aliases script to `~/.cc-switch/aliases.sh`.
pub fn write_aliases_file(script: &str) -> Result<PathBuf, AppError> {
    let dir = get_app_config_dir();
    let path = dir.join("aliases.sh");
    fs::write(&path, script)
        .map_err(|e| AppError::Message(format!("写入 aliases.sh 失败: {e}")))?;
    Ok(path)
}

/// Get the path to the aliases file.
pub fn get_aliases_file_path() -> PathBuf {
    get_app_config_dir().join("aliases.sh")
}

/// Ensure the shell config file sources `~/.cc-switch/aliases.sh`.
///
/// Detects the user's shell from `$SHELL` and appends a source line to the
/// appropriate config file (`.zshrc` / `.bashrc` / `.bash_profile`) if not already present.
///
/// Returns `true` if the line was newly added, `false` if it was already there.
pub fn ensure_shell_sourced(aliases_path: &Path) -> Result<bool, AppError> {
    let shell_config = detect_shell_config()?;
    let source_line = format!(
        "[ -f {} ] && source {}",
        aliases_path.display(),
        aliases_path.display()
    );

    let existing = fs::read_to_string(&shell_config).unwrap_or_default();

    // Already sourced?
    if existing.contains(SOURCE_MARKER) || existing.contains(aliases_path.to_str().unwrap_or("")) {
        return Ok(false);
    }

    // Append source block
    let to_append = format!(
        "\n{SOURCE_MARKER}\n{source_line}\n"
    );

    fs::OpenOptions::new()
        .append(true)
        .create(true)
        .open(&shell_config)
        .and_then(|mut f| {
            use std::io::Write;
            f.write_all(to_append.as_bytes())
        })
        .map_err(|e| {
            AppError::Message(format!(
                "写入 shell 配置文件 {} 失败: {e}",
                shell_config.display()
            ))
        })?;

    Ok(true)
}

fn ensure_directory_on_shell_path(dir: &Path) -> Result<bool, AppError> {
    if path_contains(dir) {
        return Ok(false);
    }

    let shell_config = detect_shell_config()?;
    let existing = fs::read_to_string(&shell_config).unwrap_or_default();
    let dir_text = dir.to_string_lossy();
    if existing.contains(PATH_MARKER) || existing.contains(dir_text.as_ref()) {
        return Ok(false);
    }

    let to_append = format!("\n{PATH_MARKER}\nexport PATH=\"{}:$PATH\"\n", dir_text);
    fs::OpenOptions::new()
        .append(true)
        .create(true)
        .open(&shell_config)
        .and_then(|mut f| {
            use std::io::Write;
            f.write_all(to_append.as_bytes())
        })
        .map_err(|e| {
            AppError::Message(format!(
                "写入 shell PATH 配置 {} 失败: {e}",
                shell_config.display()
            ))
        })?;

    Ok(true)
}

fn path_contains(target: &Path) -> bool {
    let Ok(path_var) = env::var("PATH") else {
        return false;
    };

    env::split_paths(&path_var).any(|entry| entry == target)
}

fn alias_launcher_dir() -> Result<PathBuf, AppError> {
    let home = dirs::home_dir()
        .ok_or_else(|| AppError::Message("无法获取 HOME 目录".to_string()))?;

    let preferred = [home.join(".local/bin"), home.join("bin"), get_app_config_dir().join("bin")];
    for candidate in preferred {
        if path_contains(&candidate) && ensure_directory_writable(&candidate)? {
            return Ok(candidate);
        }
    }

    let Ok(path_var) = env::var("PATH") else {
        let fallback = home.join(".local/bin");
        ensure_directory_writable(&fallback)?;
        return Ok(fallback);
    };

    for entry in env::split_paths(&path_var) {
        if !is_supported_launcher_dir(&entry, &home) {
            continue;
        }
        if ensure_directory_writable(&entry)? {
            return Ok(entry);
        }
    }

    let fallback = home.join(".local/bin");
    ensure_directory_writable(&fallback)?;
    Ok(fallback)
}

fn is_supported_launcher_dir(entry: &Path, home: &Path) -> bool {
    entry.starts_with(home)
        || entry == Path::new("/usr/local/bin")
        || entry == Path::new("/opt/homebrew/bin")
}

fn ensure_directory_writable(dir: &Path) -> Result<bool, AppError> {
    fs::create_dir_all(dir).map_err(|e| AppError::io(dir, e))?;

    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let probe = dir.join(format!(".cc-switch-write-test-{stamp}-{}", std::process::id()));
    match fs::write(&probe, b"") {
        Ok(()) => {
            let _ = fs::remove_file(&probe);
            Ok(true)
        }
        Err(err) => {
            if err.kind() == std::io::ErrorKind::PermissionDenied {
                Ok(false)
            } else {
                Err(AppError::io(dir, err))
            }
        }
    }
}

fn cleanup_managed_launchers(dir: &Path, expected: &HashSet<String>) -> Result<(), AppError> {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(err) => return Err(AppError::io(dir, err)),
    };

    for entry in entries {
        let entry = entry.map_err(|e| AppError::io(dir, e))?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }

        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if !file_name.starts_with("claude-") || expected.contains(file_name) {
            continue;
        }

        let contents = match fs::read_to_string(&path) {
            Ok(contents) => contents,
            Err(_) => continue,
        };
        if contents.contains(SCRIPT_HEADER) {
            fs::remove_file(&path).map_err(|e| AppError::io(&path, e))?;
        }
    }

    Ok(())
}

fn write_alias_launchers(
    providers: &IndexMap<String, Provider>,
    current_id: &str,
) -> Result<(), AppError> {
    let commands = collect_alias_commands(providers, current_id);
    let dir = alias_launcher_dir()?;

    let expected: HashSet<String> = commands
        .iter()
        .map(|command| command.command_name.clone())
        .collect();

    cleanup_managed_launchers(&dir, &expected)?;

    for command in commands {
        let path = dir.join(&command.command_name);
        let script = generate_launcher_script(&command);
        fs::write(&path, script).map_err(|e| AppError::io(&path, e))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;

            let mut perms = fs::metadata(&path)
                .map_err(|e| AppError::io(&path, e))?
                .permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&path, perms).map_err(|e| AppError::io(&path, e))?;
        }
    }

    let _ = ensure_directory_on_shell_path(&dir);
    Ok(())
}

/// Detect the shell config file path based on `$SHELL`.
fn detect_shell_config() -> Result<PathBuf, AppError> {
    let home = dirs::home_dir()
        .ok_or_else(|| AppError::Message("无法获取 HOME 目录".to_string()))?;

    let shell = std::env::var("SHELL").unwrap_or_default();
    let config = if shell.contains("zsh") {
        home.join(".zshrc")
    } else if shell.contains("bash") {
        // Prefer .bashrc on Linux; .bash_profile on macOS (where .bashrc is not auto-sourced)
        let bashrc = home.join(".bashrc");
        let bash_profile = home.join(".bash_profile");
        if bash_profile.exists() && !bashrc.exists() {
            bash_profile
        } else {
            bashrc
        }
    } else {
        // Fallback: try .profile
        home.join(".profile")
    };

    Ok(config)
}

/// Convenience: regenerate and write the aliases file for all Claude providers.
///
/// Also ensures the shell config is set up to source the file (one-time).
/// Silently ignores errors to avoid interrupting the main provider operation.
pub fn refresh_aliases(providers: &IndexMap<String, Provider>, current_id: &str) {
    let script = generate_aliases_script(providers, current_id);
    match write_aliases_file(&script) {
        Ok(path) => {
            let _ = ensure_shell_sourced(&path);
            if let Err(err) = write_alias_launchers(providers, current_id) {
                log::warn!("Failed to write alias launchers: {err}");
            }
        }
        Err(e) => {
            log::warn!("Failed to write aliases file: {e}");
        }
    }
}
