//! Claude alias launcher generation.
//!
//! Claude aliases are provided as real executable launcher scripts (for example
//! `~/.local/bin/claude-mini`) instead of shell functions. This avoids stale
//! in-memory shell definitions after users edit and save providers in the app.
//!
//! `~/.cc-switch/aliases.sh` is kept as an informational file for backwards
//! compatibility, but commands should resolve through the launcher directory.

use crate::config::get_app_config_dir;
use crate::error::AppError;
use crate::provider::Provider;
use crate::services::provider::sanitize_claude_settings_for_live;
use indexmap::IndexMap;
use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const PATH_MARKER: &str = "# cc-switch alias bin";
const SCRIPT_HEADER: &str = "# Generated by cc-switch — do not edit manually";

/// Generate the shell script content for all non-current Claude providers with an alias set.
///
/// The current provider is excluded because it already maps to the global `claude` command
/// (written to `~/.claude/settings.json` by cc-switch).
pub fn generate_aliases_script(
    providers: &IndexMap<String, Provider>,
    current_id: &str,
) -> String {
    let commands = collect_alias_commands(providers, current_id);
    let mut lines = Vec::new();
    lines.push(SCRIPT_HEADER.to_string());
    lines.push("# Claude aliases are provided as executable launcher scripts in your PATH.".to_string());
    lines.push("# This file is informational only and does not define shell functions.".to_string());
    lines.push("# The current active provider is already mapped to the `claude` command.".to_string());
    lines.push(String::new());

    if commands.is_empty() {
        lines.push("# No aliases configured. Set an alias on a Claude provider to generate launcher commands here.".to_string());
        return lines.join("\n");
    }

    lines.push("# Available commands:".to_string());
    for command in commands {
        lines.push(format!("# - {}", command.command_name));
    }

    lines.join("\n")
}

/// Minimally quote a shell value: wrap in single quotes and escape embedded single quotes.
fn shell_quote(s: &str) -> String {
    // Use single quotes for safety; escape any embedded single quotes as '\''
    let escaped = s.replace('\'', r"'\''");
    format!("'{escaped}'")
}

#[derive(Debug, Clone)]
struct AliasCommand {
    command_name: String,
    home_dir: PathBuf,
    settings_json: String,
}

fn collect_alias_commands(
    providers: &IndexMap<String, Provider>,
    current_id: &str,
) -> Vec<AliasCommand> {
    let mut commands = Vec::new();
    for (id, provider) in providers {
        if id.as_str() == current_id {
            continue;
        }

        let alias_name = match &provider.alias {
            Some(a) if !a.trim().is_empty() => a.trim().to_string(),
            _ => continue,
        };

        let settings = sanitize_claude_settings_for_live(&provider.settings_config);
        let has_env = settings
            .get("env")
            .and_then(|value| value.as_object())
            .is_some_and(|env| !env.is_empty());
        if !has_env {
            continue;
        }

        let Ok(settings_json) = serde_json::to_string_pretty(&settings) else {
            continue;
        };

        commands.push(AliasCommand {
            command_name: format!("claude-{alias_name}"),
            home_dir: get_alias_home_dir(&alias_name),
            settings_json,
        });
    }
    commands
}

fn generate_launcher_script(command: &AliasCommand) -> String {
    let mut lines = vec![
        "#!/bin/sh".to_string(),
        SCRIPT_HEADER.to_string(),
        format!("# Command: {}", command.command_name),
        String::new(),
    ];

    lines.push(format!(
        "export HOME={}",
        shell_quote(command.home_dir.to_string_lossy().as_ref())
    ));
    lines.push(r#"exec claude "$@""#.to_string());
    lines.push(String::new());
    lines.join("\n")
}

/// Write the aliases script to `~/.cc-switch/aliases.sh`.
pub fn write_aliases_file(script: &str) -> Result<PathBuf, AppError> {
    let dir = get_app_config_dir();
    let path = dir.join("aliases.sh");
    fs::write(&path, script)
        .map_err(|e| AppError::Message(format!("写入 aliases.sh 失败: {e}")))?;
    Ok(path)
}

/// Get the path to the aliases file.
pub fn get_aliases_file_path() -> PathBuf {
    get_app_config_dir().join("aliases.sh")
}

fn get_alias_homes_dir() -> PathBuf {
    get_app_config_dir().join("alias-homes")
}

fn get_alias_home_dir(alias_name: &str) -> PathBuf {
    get_alias_homes_dir().join(alias_name)
}

fn get_alias_claude_dir(alias_name: &str) -> PathBuf {
    get_alias_home_dir(alias_name).join(".claude")
}

fn get_alias_settings_path(alias_name: &str) -> PathBuf {
    get_alias_claude_dir(alias_name).join("settings.json")
}

fn real_claude_dir() -> Result<PathBuf, AppError> {
    let home = dirs::home_dir()
        .ok_or_else(|| AppError::Message("无法获取 HOME 目录".to_string()))?;
    Ok(home.join(".claude"))
}

fn ensure_directory_on_shell_path(dir: &Path) -> Result<bool, AppError> {
    if path_contains(dir) {
        return Ok(false);
    }

    let shell_config = detect_shell_config()?;
    let existing = fs::read_to_string(&shell_config).unwrap_or_default();
    let dir_text = dir.to_string_lossy();
    if existing.contains(PATH_MARKER) || existing.contains(dir_text.as_ref()) {
        return Ok(false);
    }

    let to_append = format!("\n{PATH_MARKER}\nexport PATH=\"{}:$PATH\"\n", dir_text);
    fs::OpenOptions::new()
        .append(true)
        .create(true)
        .open(&shell_config)
        .and_then(|mut f| {
            use std::io::Write;
            f.write_all(to_append.as_bytes())
        })
        .map_err(|e| {
            AppError::Message(format!(
                "写入 shell PATH 配置 {} 失败: {e}",
                shell_config.display()
            ))
        })?;

    Ok(true)
}

fn path_contains(target: &Path) -> bool {
    let Ok(path_var) = env::var("PATH") else {
        return false;
    };

    env::split_paths(&path_var).any(|entry| entry == target)
}

fn alias_launcher_dir() -> Result<PathBuf, AppError> {
    let home = dirs::home_dir()
        .ok_or_else(|| AppError::Message("无法获取 HOME 目录".to_string()))?;

    let preferred = [home.join(".local/bin"), home.join("bin"), get_app_config_dir().join("bin")];
    for candidate in preferred {
        if path_contains(&candidate) && ensure_directory_writable(&candidate)? {
            return Ok(candidate);
        }
    }

    let Ok(path_var) = env::var("PATH") else {
        let fallback = home.join(".local/bin");
        ensure_directory_writable(&fallback)?;
        return Ok(fallback);
    };

    for entry in env::split_paths(&path_var) {
        if !is_supported_launcher_dir(&entry, &home) {
            continue;
        }
        if ensure_directory_writable(&entry)? {
            return Ok(entry);
        }
    }

    let fallback = home.join(".local/bin");
    ensure_directory_writable(&fallback)?;
    Ok(fallback)
}

fn is_supported_launcher_dir(entry: &Path, home: &Path) -> bool {
    entry.starts_with(home)
        || entry == Path::new("/usr/local/bin")
        || entry == Path::new("/opt/homebrew/bin")
}

fn ensure_directory_writable(dir: &Path) -> Result<bool, AppError> {
    fs::create_dir_all(dir).map_err(|e| AppError::io(dir, e))?;

    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let probe = dir.join(format!(".cc-switch-write-test-{stamp}-{}", std::process::id()));
    match fs::write(&probe, b"") {
        Ok(()) => {
            let _ = fs::remove_file(&probe);
            Ok(true)
        }
        Err(err) => {
            if err.kind() == std::io::ErrorKind::PermissionDenied {
                Ok(false)
            } else {
                Err(AppError::io(dir, err))
            }
        }
    }
}

fn cleanup_managed_launchers(dir: &Path, expected: &HashSet<String>) -> Result<(), AppError> {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(err) => return Err(AppError::io(dir, err)),
    };

    for entry in entries {
        let entry = entry.map_err(|e| AppError::io(dir, e))?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }

        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if !file_name.starts_with("claude-") || expected.contains(file_name) {
            continue;
        }

        let contents = match fs::read_to_string(&path) {
            Ok(contents) => contents,
            Err(_) => continue,
        };
        if contents.contains(SCRIPT_HEADER) {
            fs::remove_file(&path).map_err(|e| AppError::io(&path, e))?;
        }
    }

    Ok(())
}

fn cleanup_alias_homes(dir: &Path, expected: &HashSet<String>) -> Result<(), AppError> {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(err) => return Err(AppError::io(dir, err)),
    };

    for entry in entries {
        let entry = entry.map_err(|e| AppError::io(dir, e))?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }

        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if expected.contains(file_name) {
            continue;
        }

        if path.is_dir() {
            fs::remove_dir_all(&path).map_err(|e| AppError::io(&path, e))?;
        } else {
            fs::remove_file(&path).map_err(|e| AppError::io(&path, e))?;
        }
    }

    Ok(())
}

#[cfg(unix)]
fn create_symlink(src: &Path, dst: &Path) -> Result<(), AppError> {
    std::os::unix::fs::symlink(src, dst).map_err(|e| AppError::io(dst, e))
}

fn mirror_claude_home(alias_name: &str) -> Result<(), AppError> {
    let source_dir = real_claude_dir()?;
    let target_dir = get_alias_claude_dir(alias_name);
    fs::create_dir_all(&target_dir).map_err(|e| AppError::io(&target_dir, e))?;

    let entries = match fs::read_dir(&source_dir) {
        Ok(entries) => entries,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(err) => return Err(AppError::io(&source_dir, err)),
    };

    for entry in entries {
        let entry = entry.map_err(|e| AppError::io(&source_dir, e))?;
        let file_name = entry.file_name();
        let Some(file_name_str) = file_name.to_str() else {
            continue;
        };
        if file_name_str == "settings.json" {
            continue;
        }

        let target = target_dir.join(&file_name);
        if target.exists() {
            continue;
        }
        create_symlink(&entry.path(), &target)?;
    }

    Ok(())
}

fn write_alias_homes(
    providers: &IndexMap<String, Provider>,
    current_id: &str,
) -> Result<Vec<AliasCommand>, AppError> {
    let commands = collect_alias_commands(providers, current_id);
    let dir = get_alias_homes_dir();
    fs::create_dir_all(&dir).map_err(|e| AppError::io(&dir, e))?;

    let expected: HashSet<String> = commands
        .iter()
        .filter_map(|command| command.home_dir.file_name().and_then(|name| name.to_str()).map(str::to_string))
        .collect();
    cleanup_alias_homes(&dir, &expected)?;

    for command in &commands {
        let alias_name = command
            .home_dir
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| AppError::Message("alias home directory is invalid".to_string()))?;
        mirror_claude_home(alias_name)?;

        let settings_path = get_alias_settings_path(alias_name);
        fs::write(&settings_path, &command.settings_json)
            .map_err(|e| AppError::io(&settings_path, e))?;
    }

    Ok(commands)
}

fn write_alias_launchers(
    providers: &IndexMap<String, Provider>,
    current_id: &str,
) -> Result<(), AppError> {
    let commands = write_alias_homes(providers, current_id)?;
    let dir = alias_launcher_dir()?;

    let expected: HashSet<String> = commands
        .iter()
        .map(|command| command.command_name.clone())
        .collect();

    cleanup_managed_launchers(&dir, &expected)?;

    for command in commands {
        let path = dir.join(&command.command_name);
        let script = generate_launcher_script(&command);
        fs::write(&path, script).map_err(|e| AppError::io(&path, e))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;

            let mut perms = fs::metadata(&path)
                .map_err(|e| AppError::io(&path, e))?
                .permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&path, perms).map_err(|e| AppError::io(&path, e))?;
        }
    }

    let _ = ensure_directory_on_shell_path(&dir);
    Ok(())
}

/// Detect the shell config file path based on `$SHELL`.
fn detect_shell_config() -> Result<PathBuf, AppError> {
    let home = dirs::home_dir()
        .ok_or_else(|| AppError::Message("无法获取 HOME 目录".to_string()))?;

    let shell = std::env::var("SHELL").unwrap_or_default();
    let config = if shell.contains("zsh") {
        home.join(".zshrc")
    } else if shell.contains("bash") {
        // Prefer .bashrc on Linux; .bash_profile on macOS (where .bashrc is not auto-sourced)
        let bashrc = home.join(".bashrc");
        let bash_profile = home.join(".bash_profile");
        if bash_profile.exists() && !bashrc.exists() {
            bash_profile
        } else {
            bashrc
        }
    } else {
        // Fallback: try .profile
        home.join(".profile")
    };

    Ok(config)
}

/// Convenience: regenerate launcher scripts and the informational aliases file.
///
/// Silently ignores errors to avoid interrupting the main provider operation.
pub fn refresh_aliases(providers: &IndexMap<String, Provider>, current_id: &str) {
    let script = generate_aliases_script(providers, current_id);
    match write_aliases_file(&script) {
        Ok(_) => {
            if let Err(err) = write_alias_launchers(providers, current_id) {
                log::warn!("Failed to write alias launchers: {err}");
            }
        }
        Err(e) => {
            log::warn!("Failed to write aliases file: {e}");
        }
    }
}
