//! Shell alias generation for Claude providers.
//!
//! Generates a shell script (`~/.cc-switch/aliases.sh`) containing shell functions
//! for each non-current Claude provider that has an alias configured. This allows
//! users to run multiple providers simultaneously by using different terminal commands.
//!
//! Usage example:
//! - Current provider (Kimi) → `claude` command (already configured globally)
//! - Alibaba provider with alias "alibaba" → `claude-alibaba` function
//! - DeepSeek provider with alias "deepseek" → `claude-deepseek` function

use crate::config::get_app_config_dir;
use crate::error::AppError;
use crate::provider::Provider;
use indexmap::IndexMap;
use std::fs;
use std::path::{Path, PathBuf};

const SOURCE_MARKER: &str = "# cc-switch shell aliases";

/// Generate the shell script content for all non-current Claude providers with an alias set.
///
/// The current provider is excluded because it already maps to the global `claude` command
/// (written to `~/.claude/settings.json` by cc-switch).
pub fn generate_aliases_script(
    providers: &IndexMap<String, Provider>,
    current_id: &str,
) -> String {
    let mut lines = Vec::new();
    lines.push("# Generated by cc-switch — do not edit manually".to_string());
    lines.push("# Each function below invokes `claude` with a specific provider's environment variables.".to_string());
    lines.push("# The current active provider is already mapped to the `claude` command.".to_string());
    lines.push(String::new());

    let mut has_any = false;

    for (id, provider) in providers {
        // Skip current provider (it's already `claude`)
        if id.as_str() == current_id {
            continue;
        }

        let alias_name = match &provider.alias {
            Some(a) if !a.trim().is_empty() => a.trim().to_string(),
            _ => continue,
        };

        let env_vars = extract_env_vars(provider);
        if env_vars.is_empty() {
            continue;
        }

        has_any = true;
        let func_name = format!("claude-{alias_name}");

        lines.push(format!("{}() {{", func_name));
        for (k, v) in &env_vars {
            lines.push(format!("  {}={} \\", k, shell_quote(v)));
        }
        lines.push(r#"  claude "$@""#.to_string());
        lines.push("}".to_string());
        lines.push(String::new());
    }

    if !has_any {
        lines.push("# No aliases configured. Set an alias on a Claude provider to generate functions here.".to_string());
    }

    lines.join("\n")
}

/// Extract env vars from a Claude provider's settingsConfig.env, in a stable order.
///
/// Returns only non-empty values. Sensitive fields (API keys) are included as-is
/// since the file is stored in the user's home directory.
fn extract_env_vars(provider: &Provider) -> Vec<(String, String)> {
    let env = match provider.settings_config.get("env") {
        Some(e) => e,
        None => return vec![],
    };

    let priority_keys = [
        "ANTHROPIC_BASE_URL",
        "ANTHROPIC_AUTH_TOKEN",
        "ANTHROPIC_API_KEY",
        "ANTHROPIC_MODEL",
        "ANTHROPIC_REASONING_MODEL",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL",
        "ANTHROPIC_DEFAULT_SONNET_MODEL",
        "ANTHROPIC_DEFAULT_OPUS_MODEL",
    ];

    let mut result = Vec::new();
    for key in &priority_keys {
        if let Some(val) = env.get(key).and_then(|v| v.as_str()) {
            if !val.is_empty() {
                result.push((key.to_string(), val.to_string()));
            }
        }
    }

    // Also pick up any extra keys not in the priority list
    if let Some(obj) = env.as_object() {
        for (k, v) in obj {
            if priority_keys.contains(&k.as_str()) {
                continue; // already added
            }
            if let Some(s) = v.as_str() {
                if !s.is_empty() {
                    result.push((k.clone(), s.to_string()));
                }
            }
        }
    }

    result
}

/// Minimally quote a shell value: wrap in single quotes and escape embedded single quotes.
fn shell_quote(s: &str) -> String {
    // Use single quotes for safety; escape any embedded single quotes as '\''
    let escaped = s.replace('\'', r"'\''");
    format!("'{escaped}'")
}

/// Write the aliases script to `~/.cc-switch/aliases.sh`.
pub fn write_aliases_file(script: &str) -> Result<PathBuf, AppError> {
    let dir = get_app_config_dir();
    let path = dir.join("aliases.sh");
    fs::write(&path, script)
        .map_err(|e| AppError::Message(format!("写入 aliases.sh 失败: {e}")))?;
    Ok(path)
}

/// Get the path to the aliases file.
pub fn get_aliases_file_path() -> PathBuf {
    get_app_config_dir().join("aliases.sh")
}

/// Ensure the shell config file sources `~/.cc-switch/aliases.sh`.
///
/// Detects the user's shell from `$SHELL` and appends a source line to the
/// appropriate config file (`.zshrc` / `.bashrc` / `.bash_profile`) if not already present.
///
/// Returns `true` if the line was newly added, `false` if it was already there.
pub fn ensure_shell_sourced(aliases_path: &Path) -> Result<bool, AppError> {
    let shell_config = detect_shell_config()?;
    let source_line = format!(
        "[ -f {} ] && source {}",
        aliases_path.display(),
        aliases_path.display()
    );

    let existing = fs::read_to_string(&shell_config).unwrap_or_default();

    // Already sourced?
    if existing.contains(SOURCE_MARKER) || existing.contains(aliases_path.to_str().unwrap_or("")) {
        return Ok(false);
    }

    // Append source block
    let to_append = format!(
        "\n{SOURCE_MARKER}\n{source_line}\n"
    );

    fs::OpenOptions::new()
        .append(true)
        .create(true)
        .open(&shell_config)
        .and_then(|mut f| {
            use std::io::Write;
            f.write_all(to_append.as_bytes())
        })
        .map_err(|e| {
            AppError::Message(format!(
                "写入 shell 配置文件 {} 失败: {e}",
                shell_config.display()
            ))
        })?;

    Ok(true)
}

/// Detect the shell config file path based on `$SHELL`.
fn detect_shell_config() -> Result<PathBuf, AppError> {
    let home = dirs::home_dir()
        .ok_or_else(|| AppError::Message("无法获取 HOME 目录".to_string()))?;

    let shell = std::env::var("SHELL").unwrap_or_default();
    let config = if shell.contains("zsh") {
        home.join(".zshrc")
    } else if shell.contains("bash") {
        // Prefer .bashrc on Linux; .bash_profile on macOS (where .bashrc is not auto-sourced)
        let bashrc = home.join(".bashrc");
        let bash_profile = home.join(".bash_profile");
        if bash_profile.exists() && !bashrc.exists() {
            bash_profile
        } else {
            bashrc
        }
    } else {
        // Fallback: try .profile
        home.join(".profile")
    };

    Ok(config)
}

/// Convenience: regenerate and write the aliases file for all Claude providers.
///
/// Also ensures the shell config is set up to source the file (one-time).
/// Silently ignores errors to avoid interrupting the main provider operation.
pub fn refresh_aliases(providers: &IndexMap<String, Provider>, current_id: &str) {
    let script = generate_aliases_script(providers, current_id);
    match write_aliases_file(&script) {
        Ok(path) => {
            let _ = ensure_shell_sourced(&path);
        }
        Err(e) => {
            log::warn!("Failed to write aliases file: {e}");
        }
    }
}
